Yii auto-instrumentation demo and docs
open-telemetry/opentelemetry-php-contrib pull request #225
Opened 2023-12-26 07:04 UTC by runtu666

2023-12-26 16:34 UTC, weslenteche requested changes

2023-12-26 16:34 UTC, weslenteche commented on examples/instrumentation/yii/README.md
> +2. for nginx users please view [the fpm directory](/examples/instrumentation/yii/apache/README.md).
```suggestion
2. for nginx users please view [the fpm directory](/examples/instrumentation/yii/fpm/README.md).
```

2023-12-27 05:30 UTC, brettmc commented on README.md
> +- The documentation for the Yii context can be found [here](/src/Instrumentation/Yii/README.md).
```suggestion
- The documentation for Yii framework can be found [here](/src/Instrumentation/Yii/README.md).
```

2023-12-27 09:21 UTC, brettmc approved these changes

2023-12-27 09:29 UTC, runtu666 commented
> Thanks for opening your first pull request! If you haven't yet signed our Contributor License Agreement (CLA), then please do so that we can accept your contribution. A link should appear shortly in this PR if you have not already signed one.

no link send to me

2023-12-27 11:24 UTC, merged