feat: implement cloud{provider,platform}, aws.{ecs.*,log.*} in ECS detector
open-telemetry/opentelemetry-php-contrib pull request #83
Opened 2022-10-29 15:25 UTC by mmanciop

This PR is the look-alike of others like https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1083, https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1212 and https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2626.

2022-10-30 22:11 UTC, brettmc requested changes
Welcome and thanks for your contribution. This looks good, just a couple of small issues/improvements from me.

2022-10-31 08:26 UTC, mmanciop commented on src/Aws/src/Ecs/Detector.php
> +     * -
Yeah they remained in the keyboard :-)

Done in 8260f9a

2022-10-31 08:44 UTC, mmanciop commented on src/Aws/src/Ecs/Detector.php
>              // TODO: add 'Process is not running on ECS' when logs are added
Done in 94c7d9a59131319f915b18fe9db92654648169ea

2022-10-31 23:32 UTC, brettmc approved these changes

2022-11-02 09:15 UTC, mmanciop commented
@brettmc what needs to happen before we can merge this?

2022-11-02 12:07 UTC, bobstrecansky commented
@mmanciop - merging now! :)

2022-11-02 12:07 UTC, merged